server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/vocab_dev
    hikari:
      username: vocab_dev
      password: asdcxz123
  flyway:
    url: ${spring.datasource.url}
    schemas: public
    user: ${spring.datasource.hikari.username}
    password: ${spring.datasource.hikari.password}