version: '2'
services:
  vocab:
    image: jeksvp/vocab
    restart: always
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://host.docker.internal:5432/vocab_dev
      DATABASE_USERNAME: vocab_dev
      DATABASE_PASSWORD: asdcxz123
    ports:
      - 8080:8080